<?php

namespace nehero;

class FriendlyTimezone 
{
	/**
	 * @var array
	 */
	public $timezones = [
		//"(GMT-12:00) International Date Line West" => "" ,
		"(GMT-11:00) Midway Island, Samoa" => "Pacific/Midway",
		"(GMT-10:00) Hawaii" => "Pacific/Honolulu",
		"(GMT-09:00) Alaska" => "America/Anchorage",
		"(GMT-08:00) Pacific Time (US and Canada); Tijuana" => "America/Tijuana",
		"(GMT-08:00) Tijuana, Baja California" => "America/Tijuana",
		"(GMT-07:00) Mountain Time (US and Canada)" => "America/Edmonton",
		"(GMT-07:00) Chihuahua, La Paz, Mazatlan" => "America/Chihuahua",
		"(GMT-07:00) Arizona" => "America/Phoenix",
		"(GMT-06:00) Central Time (US and Canada)" => "America/Chicago",
		"(GMT-06:00) Saskatchewan" => "America/Regina",
		"(GMT-06:00) Guadalajara, Mexico City, Monterrey" => "America/Mexico_City",
		"(GMT-06:00) Central America" => "America/Managua",
		"(GMT-05:00) Eastern Time (US and Canada)" => "America/New_York",
		"(GMT-05:00) Indiana (East)" => "America/Indiana/Indianapolis",
		"(GMT-05:00) Bogota, Lima, Quito" => "America/Bogota",
		"(GMT-04:30) Caracas" => "America/Caracas",
		"(GMT-04:00) Atlantic Time (Canada)" => "America/Halifax",
		"(GMT-04:00) Georgetown, La Paz, San Juan" => "America/Argentina/San_Juan",
		"(GMT-04:00) Santiago" => "America/Santiago",
		"(GMT-04:00) Manaus" => "America/Manaus",
		"(GMT-04:00) Asuncion" => "America/Asuncion",
		"(GMT-03:30) Newfoundland" => "America/St_Johns",
		"(GMT-03:00) Brasilia" => "America/Sao_Paulo",
		"(GMT-03:00) Buenos Aires" => "America/Argentina/Buenos_Aires",
		"(GMT-03:00) Georgetown" => "America/Argentina/Buenos_Aires",
		"(GMT-03:00) Greenland" => "America/Godthab",
		"(GMT-03:00) Montevideo" => "America/Montevideo",
		"(GMT-02:00) Mid-Atlantic" => "Atlantic/South_Georgia",
		"(GMT-01:00) Azores" => "Atlantic/Azores",
		"(GMT-01:00) Cape Verde Islands" => "Atlantic/Cape_Verde",
		"(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London" => "Europe/London",
		"(GMT) Monrovia, Reykjavik" => "Atlantic/Reykjavik",
		"(GMT) Casablanca" => "Africa/Casablanca",
		"(GMT) Coordinated Universal Time" => "UTC",
		"(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague" => "Europe/Belgrade",
		"(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb" => "Europe/Sarajevo",
		"(GMT+01:00) Brussels, Copenhagen, Madrid, Paris" => "Europe/Paris",
		"(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" => "Europe/Berlin",
		"(GMT+01:00) West Central Africa" => "Africa/Lagos",
		"(GMT+02:00) Amman" => "Asia/Amman",
		"(GMT+02:00) Beirut" => "Asia/Beirut",
		"(GMT+02:00) Cairo" => "Africa/Cairo",
		"(GMT+02:00) Minsk" => "Europe/Minsk",
		"(GMT+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius" => "Europe/Helsinki",
		"(GMT+02:00) Athens, Bucharest, Istanbul" => "Europe/Athens",
		"(GMT+02:00) Jerusalem" => "Asia/Jerusalem",
		"(GMT+02:00) Harare, Pretoria" => "Africa/Harare",
		"(GMT+02:00) Windhoek" => "Africa/Windhoek",
		"(GMT+03:00) Moscow, St. Petersburg, Volgograd" => "Europe/Moscow",
		"(GMT+03:00) Kuwait, Riyadh" => "Asia/Kuwait",
		"(GMT+03:00) Nairobi" => "Africa/Nairobi",
		"(GMT+03:00) Baghdad" => "Asia/Baghdad",
		"(GMT+03:00) Tbilisi" => "Asia/Tbilisi",
		"(GMT+03:30) Tehran" => "Asia/Tehran",
		"(GMT+04:00) Abu Dhabi, Muscat" => "Asia/Muscat",
		"(GMT+04:00) Baku, Tbilisi, Yerevan" => "Asia/Baku",
		"(GMT+04:00) Yerevan" => "Asia/Yerevan",
		"(GMT+04:00) Port Louis" => "Indian/Mauritius",
		"(GMT+04:30) Kabul" => "Asia/Kabul",
		"(GMT+05:00) Ekaterinburg" => "Asia/Yekaterinburg",
		"(GMT+05:00) Tashkent" => "Asia/Tashkent",
		"(GMT+05:00) Islamabad, Karachi" => "Asia/Karachi",
		"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi" => "Asia/Kolkata",
		"(GMT+05:45) Kathmandu" => "Asia/Kathmandu",
		"(GMT+06:00) Astana, Dhaka" => "Asia/Dhaka",
		"(GMT+06:00) Sri Jayawardenepura" => "Asia/Colombo",
		"(GMT+06:00) Almaty, Novosibirsk" => "Asia/Almaty",
		"(GMT+06:30) Yangon (Rangoon)" => "Asia/Rangoon",
		"(GMT+07:00) Bangkok, Hanoi, Jakarta" => "Asia/Bangkok",
		"(GMT+07:00) Krasnoyarsk" => "Asia/Krasnoyarsk",
		"(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi" => "Asia/Hong_Kong",
		"(GMT+08:00) Kuala Lumpur, Singapore" => "Asia/Kuala_Lumpur",
		"(GMT+08:00) Taipei" => "Asia/Taipei",
		"(GMT+08:00) Perth" => "Australia/Perth",
		"(GMT+08:00) Irkutsk, Ulaanbaatar" => "Asia/Irkutsk",
		"(GMT+09:00) Seoul" => "Asia/Seoul",
		"(GMT+09:00) Osaka, Sapporo, Tokyo" => "Asia/Tokyo",
		"(GMT+09:00) Yakutsk" => "Asia/Yakutsk",
		"(GMT+09:30) Darwin" => "Australia/Darwin",
		"(GMT+09:30) Adelaide" => "Australia/Adelaide",
		"(GMT+10:00) Canberra, Melbourne, Sydney" => "Australia/Sydney",
		"(GMT+10:00) Brisbane" => "Australia/Brisbane",
		"(GMT+10:00) Hobart" => "Australia/Hobart",
		"(GMT+10:00) Vladivostok" => "Asia/Vladivostok",
		"(GMT+10:00) Guam, Port Moresby" => "Pacific/Guam",
		"(GMT+11:00) Magadan, Solomon Islands, New Caledonia" => "Asia/Magadan",
		"(GMT+12:00) Fiji, Kamchatka, Marshall Is." => "Pacific/Fiji",
		"(GMT+12:00) Auckland, Wellington" => "Pacific/Auckland",
		"(GMT+12:00) Petropavlovsk-Kamchatsky" => "Asia/Kamchatka",
		"(GMT+13:00) Nuku'alofa" => "Pacific/Tongatapu",
	];

	/**
	 * @return array
	 */
	public static function list()
	{
		return self::$timezones;
	}
}